In [98]:
import pandas as pd

wine = pd.read_csv('https://bit.ly/wine_csv_data')

In [25]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   alcohol  6497 non-null   float64
 1   sugar    6497 non-null   float64
 2   pH       6497 non-null   float64
 3   class    6497 non-null   float64
dtypes: float64(4)
memory usage: 203.2 KB


In [26]:
wine.columns

Index(['alcohol', 'sugar', 'pH', 'class'], dtype='object')

In [27]:
wine.head()

alcohol  sugar    pH  class
0      9.4    1.9  3.51    0.0
1      9.8    2.6  3.20    0.0
2      9.8    2.3  3.26    0.0
3      9.8    1.9  3.16    0.0
4      9.4    1.9  3.51    0.0

In [105]:
wine['class'].unique()

array([0., 1.])

In [106]:
wine['class'].value_counts()

class
1.0    4898
0.0    1599
Name: count, dtype: int64

In [7]:
# hold-out기법

In [107]:
wine.values

array([[ 9.4 ,  1.9 ,  3.51,  0.  ],
       [ 9.8 ,  2.6 ,  3.2 ,  0.  ],
       [ 9.8 ,  2.3 ,  3.26,  0.  ],
       ...,
       [ 9.4 ,  1.2 ,  2.99,  1.  ],
       [12.8 ,  1.1 ,  3.34,  1.  ],
       [11.8 ,  0.8 ,  3.26,  1.  ]])

In [108]:
data = wine.values[:, :3]

In [109]:
wine['class'].values

array([0., 0., 0., ..., 1., 1., 1.])

In [110]:
target = wine['class']

In [111]:
from sklearn.model_selection import train_test_split

In [ ]:
# 6497개의 row

In [33]:
6497*0.8, 6497*+0.2

(5197.6, 1299.4)

In [112]:
train_input, test_input, train_target, test_target = train_test_split(
    data, target, test_size=0.2, random_state=42)

In [113]:
len(train_input), len(test_input)

(5197, 1300)

In [114]:
train_input.shape

(5197, 3)

In [40]:
5197*0.8, 5197*0.2

(4157.6, 1039.4)

In [115]:
sub_input, val_input, sub_target, val_target = train_test_split(
    train_input, train_target, test_size=0.2, random_state=42)

In [42]:
len(sub_input), len(val_input)

(4157, 1040)

In [43]:
sub_input.shape

(4157, 3)

In [116]:
from sklearn.tree import DecisionTreeClassifier

In [117]:
dt = DecisionTreeClassifier(random_state=42)

In [54]:
dt

DecisionTreeClassifier(random_state=42)

In [118]:
dt.fit(sub_input, sub_target)

DecisionTreeClassifier(random_state=42)

In [119]:
print(dt.score(sub_input, sub_target))
print(dt.score(val_input, val_target))

0.9971133028626413
0.864423076923077


In [48]:
# 교차 검증

In [120]:
from sklearn.model_selection import cross_validate

In [121]:
scores = cross_validate(dt, train_input, train_target)

In [51]:
scores

{'fit_time': array([0.00636792, 0.00869107, 0.00769472, 0.00825548, 0.00703502]),
 'score_time': array([0.00208807, 0.00116682, 0.00119662, 0.00154948, 0.00118256]),
 'test_score': array([0.86923077, 0.84615385, 0.87680462, 0.84889317, 0.83541867])}

In [122]:
import numpy as np

In [123]:
print(np.mean(scores['test_score']))

0.855300214703487


In [ ]:
# 검증 데이터 셋을 두는 목적이 하이퍼라마미터 튜닝을 위해서

In [ ]:
# 우리가 정해야할 하이퍼파라미터가 상당히 많음
# 분지 기준: {"지니","엔트로피","로그 손실"}, 기본값 = 지니
# 분할기 : {"최고", "랜덤"}, 기본값 = 최고
# 최대 깊이 (정수)
# min_sample_split은 정수 또는 실수형이며 기본값은 2입니다. 내부 노드를 분할하는 데 필요
# min_sample_leaf는 정수 또는 실수형이며 기본갑은 1입니다. 리프 노드에 필요한 최소 샘플
# max_features
# min_impurity_decrease는 float형 값이며 기본값은 0.0입니다.
# 노드 분할로 인해 불순물 함량이 이 값 이상 감소하는 경우 해당 노드가 분할

In [124]:
from sklearn.model_selection import GridSearchCV

params = {'min_impurity_decrease': [0.0001, 0.0002, 0.0003, 0.0004, 0.0005]}

In [125]:
gs= GridSearchCV(DecisionTreeClassifier(random_state=42), params)

In [126]:
gs.fit(train_input, train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42),
             param_grid={'min_impurity_decrease': [0.0001, 0.0002, 0.0003,
                                                   0.0004, 0.0005]})

In [127]:
gs.cv_results_

{'mean_fit_time': array([0.00528355, 0.00406895, 0.00410323, 0.00397487, 0.00453687]),
 'std_fit_time': array([0.00052521, 0.0001697 , 0.00019534, 0.00027283, 0.00041177]),
 'mean_score_time': array([0.00100098, 0.00077372, 0.00098782, 0.00092921, 0.00114326]),
 'std_score_time': array([2.17989621e-04, 8.60986764e-05, 2.53906693e-04, 1.42654393e-04,
        1.39610510e-04]),
 'param_min_impurity_decrease': masked_array(data=[0.0001, 0.0002, 0.0003, 0.0004, 0.0005],
              mask=[False, False, False, False, False],
        fill_value=1e+20),
 'params': [{'min_impurity_decrease': 0.0001},
  {'min_impurity_decrease': 0.0002},
  {'min_impurity_decrease': 0.0003},
  {'min_impurity_decrease': 0.0004},
  {'min_impurity_decrease': 0.0005}],
 'split0_test_score': array([0.86923077, 0.87115385, 0.86923077, 0.86923077, 0.86538462]),
 'split1_test_score': array([0.86826923, 0.86346154, 0.85961538, 0.86346154, 0.86923077]),
 'split2_test_score': array([0.8825794 , 0.87680462, 0.87584216, 0.88

In [128]:
best_index = np.argmax(gs.cv_results_['mean_test_score'])

In [129]:
best_index

np.int64(0)

In [130]:
print(gs.cv_results_['params'][best_index])

{'min_impurity_decrease': 0.0001}


In [ ]:
# best_estimator
# Estimator that was chosen by the search, i.e. estimator which gave highest score (or smallest loss if specified) on the left out data. Not available if refit=False

In [131]:
dt = gs.best_estimator_

In [65]:
dt

DecisionTreeClassifier(min_impurity_decrease=0.0001, random_state=42)

In [132]:
print(dt.score(train_input, train_target))

0.9615162593804117


In [133]:
print(dt.score(test_input, test_target))

0.8653846153846154


In [134]:
print(np.max(gs.cv_results_['mean_test_score']))

0.8681929740134745


In [ ]:
# 하이퍼파라미터 조합 늘리기

In [135]:
np.arange(0.0001, 0.001, 0.0001)

array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008,
       0.0009])

In [136]:
params = {'min_impurity_decrease': np.arange(0.0001, 0.001, 0.0001),
          'max_depth': range(5, 20, 1),
          'min_samples_split': range(2, 100, 10)
          }

In [137]:
gs = GridSearchCV(DecisionTreeClassifier(random_state=42), params, n_jobs=-1)
gs.fit(train_input, train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': range(5, 20),
                         'min_impurity_decrease': array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008,
       0.0009]),
                         'min_samples_split': range(2, 100, 10)})

In [138]:
print(gs.best_params_)

{'max_depth': 14, 'min_impurity_decrease': np.float64(0.0004), 'min_samples_split': 12}


In [139]:
print(np.max(gs.cv_results_['mean_test_score']))

0.8683865773302731


In [ ]:
# 균등 분포

In [ ]:
# 

In [140]:
import numpy as np

In [141]:
np.random.randint(0,10)

2

In [142]:
from scipy.stats import uniform, randint

In [143]:
rgen = randint(0, 10)

In [86]:
rgen

In [144]:
rgen.rvs(10)

array([2, 0, 4, 6, 8, 7, 8, 9, 4, 1])

In [145]:
np.unique(rgen.rvs(10000), return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 999, 1013, 1015,  995,  979,  999, 1018, 1010,  924, 1048]))

In [146]:
ugen = uniform(0, 1)
ugen.rvs(10)

array([0.9438461 , 0.56850453, 0.53953334, 0.35535655, 0.18138982,
       0.98226594, 0.4319619 , 0.89533238, 0.65827512, 0.30083863])

In [147]:
params = {'min_impurity_decrease': uniform(0.0001, 0.001),
          'max_depth': randint(20, 50),
          'min_samples_split': randint(2, 25),
          'min_samples_leaf': randint(1, 25),
          }

In [148]:
from sklearn.model_selection import RandomizedSearchCV

gs = RandomizedSearchCV(DecisionTreeClassifier(random_state=42), params,
                        n_iter=100, n_jobs=-1, random_state=42)
gs.fit(train_input, train_target)

RandomizedSearchCV(estimator=DecisionTreeClassifier(random_state=42),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000014095223890>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x0000014095378D60>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000014095220F50>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000140952225D0>},
                   random_state=42)

In [ ]:
# 그리드서치로 하이퍼파라미터 최적화 후 최종 성능 0.8681929740134745

In [149]:
print(gs.best_params_)

{'max_depth': 39, 'min_impurity_decrease': np.float64(0.00034102546602601173), 'min_samples_leaf': 7, 'min_samples_split': 13}


In [150]:
print(np.max(gs.cv_results_['mean_test_score']))

0.8695428296438884


In [155]:
dt = gs.best_estimator_

print(dt.score(test_input, test_target))

0.86


In [ ]:
# 교차검증
# test_input_split

In [ ]:
# splitter를 random으로 변경

In [156]:
gs = RandomizedSearchCV(DecisionTreeClassifier(splitter='random', random_state=42), params,
                        n_iter=100, n_jobs=-1, random_state=42)
gs.fit(train_input, train_target)

RandomizedSearchCV(estimator=DecisionTreeClassifier(random_state=42,
                                                    splitter='random'),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000014095223890>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x0000014095378D60>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000014095220F50>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000140952225D0>},
                   random_state=42)

In [157]:
print(gs.best_params_)
print(np.max(gs.cv_results_['mean_test_score']))

dt = gs.best_estimator_
print(dt.score(test_input, test_target))

{'max_depth': 43, 'min_impurity_decrease': np.float64(0.00011407982271508446), 'min_samples_leaf': 19, 'min_samples_split': 18}
0.8458726956392981
0.786923076923077
