In [3]:
import numpy as np

In [4]:
np.load('fruits_300.npy')

array([[[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]],

       [[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]],

       [[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]],

       ...,

       [[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]],

       [[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 

In [5]:
fruits=np.load('fruits_300.npy')

In [6]:
type(fruits)

numpy.ndarray

In [7]:
fruits.shape

(300, 100, 100)

In [8]:
fruits.ndim

3

In [9]:
fruits.size

3000000

In [11]:
fruits[0]

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=uint8)

In [8]:
import cv2 as cv

In [9]:
cv.imread('../img/샴1.jpg')

array([[[123, 132, 136],
        [115, 124, 128],
        [108, 118, 125],
        ...,
        [186, 182, 154],
        [187, 184, 156],
        [189, 186, 158]],

       [[115, 124, 128],
        [109, 118, 122],
        [103, 113, 120],
        ...,
        [185, 181, 153],
        [186, 183, 155],
        [188, 185, 157]],

       [[104, 115, 119],
        [ 99, 110, 114],
        [ 97, 107, 114],
        ...,
        [185, 181, 153],
        [186, 183, 155],
        [188, 185, 157]],

       ...,

       [[162, 178, 160],
        [165, 178, 162],
        [166, 176, 163],
        ...,
        [136, 149, 193],
        [137, 150, 194],
        [142, 155, 199]],

       [[162, 178, 160],
        [165, 178, 162],
        [166, 176, 163],
        ...,
        [142, 155, 199],
        [147, 160, 204],
        [146, 159, 203]],

       [[160, 179, 160],
        [163, 179, 162],
        [166, 176, 163],
        ...,
        [141, 157, 200],
        [149, 165, 208],
        [143, 159, 202]]

In [10]:
per_cat=cv.imread('../img/샴1.jpg')

In [11]:
per_cat.shape

(427, 640, 3)

In [12]:
per_cat.ndim

3

In [13]:
per_cat.size

819840

In [14]:
type(per_cat)

numpy.ndarray

In [15]:
cv.imshow('per_cat', per_cat)
cv.waitKey()
cv.destroyAllWindows() 

In [16]:
import cv2 as cv

In [17]:
cv.imread('../img/logo.jpg')

array([[[252, 249, 244],
        [250, 247, 242],
        [247, 244, 239],
        ...,
        [216, 143,  63],
        [218, 146,  68],
        [197, 125,  47]],

       [[253, 250, 245],
        [252, 249, 244],
        [250, 247, 242],
        ...,
        [219, 146,  66],
        [222, 150,  72],
        [201, 129,  51]],

       [[253, 250, 245],
        [253, 250, 245],
        [253, 250, 245],
        ...,
        [220, 147,  67],
        [223, 151,  73],
        [202, 130,  52]],

       ...,

       [[195, 174, 152],
        [196, 175, 153],
        [197, 176, 154],
        ...,
        [203, 200, 196],
        [201, 198, 194],
        [200, 197, 193]],

       [[194, 171, 149],
        [195, 172, 150],
        [196, 174, 149],
        ...,
        [205, 202, 198],
        [204, 201, 197],
        [202, 199, 195]],

       [[191, 168, 146],
        [192, 169, 147],
        [193, 171, 146],
        ...,
        [206, 203, 199],
        [205, 202, 198],
        [204, 201, 197]]

In [18]:
per_logo=cv.imread('../img/logo.jpg')

In [19]:
per_logo.shape

(480, 640, 3)

In [20]:
cv.imshow('per_logo',per_logo)
cv.waitKey()
cv.destroyAllWindows() 